name: web3kit
description: "Flutter UI Kit & Library to interact with Web3 seamlessly"
version: 0.0.1
publish_to: "none"
homepage: https://www.zupprotocol.xyz
repository: https://github.com/Zup-Protocol/web3kit

environment:
  sdk: ^3.5.2

dependencies:
  build: ^2.4.1
  build_runner: ^2.4.13
  build_runner_core: ^7.3.2
  code_builder: ^4.10.0
  collection: ^1.18.0
  dart_style: ^2.3.7
  decimal: ^3.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  hashlib: ^1.21.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  random_avatar: ^0.0.8
  shared_preferences: ^2.3.2
  shared_preferences_platform_interface: ^2.4.1
  url_launcher: ^6.3.0
  web: ^1.0.0
  zup_core:
    path: ../zup_core
    # git:
    #   url: https://github.com/Zup-Protocol/zup-core.git
    #   ref: main
  zup_ui_kit:
    path: ../zup_ui_kit
    # git:
    #   url: https://github.com/Zup-Protocol/zup-ui-kit.git
    #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.7.0
  test: ^1.25.7
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0
  mocktail_image_network: ^1.2.0
  json_serializable: ^6.8.0
  build_test: ^2.2.2

flutter_gen:
  output: lib/src/gen/
  line_length: 200
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  colors:
    enabled: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
