name: web3kit
description: "Flutter UI Kit & Library to interact with Web3 seamlessly"
version: 0.0.1
publish_to: "none"
homepage: https://www.zupprotocol.xyz
repository: https://github.com/Zup-Protocol/web3kit

environment:
  sdk: ^3.8.0
  flutter: ^3.32.2

dependencies:
  build: ^3.0.0
  build_runner: ^2.6.0
  build_runner_core: ^9.2.0
  code_builder: ^4.10.0
  collection: ^1.18.0
  dart_style: ^3.1.1
  decimal: ^3.2.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  get_it: ^7.7.0
  hashlib: ^1.21.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  random_avatar: ^0.0.8
  shared_preferences: ^2.5.2
  shared_preferences_platform_interface: ^2.4.1
  url_launcher: ^6.3.0
  web: ^1.0.0
  zup_core:
    # path: ../zup_core
    git:
      url: https://github.com/Zup-Protocol/zup-core.git
      ref: main
  zup_ui_kit:
    git:
      url: https://github.com/Zup-Protocol/zup-ui-kit.git
      ref: main

dependency_overrides:
  # zup_ui_kit:
  #   path: ../zup-ui-kit
  # zup_core:
  #   path: ../zup-core
  build: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.7.0
  test: ^1.25.7
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0
  mocktail_image_network: ^1.2.0
  json_serializable: ^6.8.0
  build_test: ^3.3.0

flutter_gen:
  output: lib/src/gen/
  line_length: 200
  integrations:
    flutter_svg: true
  assets:
    enabled: true
  colors:
    enabled: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
